# FROM tensorflow/tensorflow:1.14.0-gpu-py3
FROM nvcr.io/nvidia/tensorflow:21.03-tf1-py3
RUN apt-get -y update
# necessary to make add_user.sh work
RUN apt-get install -y --fix-missing sudo
# stuff opencv complains if they are not installed
RUN apt-get install -y --fix-missing \ 
	ffmpeg \
    libsm6 \ 
    libxext6 \
    libblas-dev \
    liblapack-dev \
    libxrender-dev \
    libgtk2.0-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    gfortran
RUN apt-get clean && rm -rf /tmp/* /var/tmp/*
RUN pip install --upgrade pip setuptools wheel
RUN pip --no-cache-dir install \
opencv-python \
scikit-image 